services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fitnexus-app
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
